TaskManagement/TaskManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('todo/', include('todo.urls')),
    path('api/', include('api.urls')),
]

TaskManagement/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'api'
urlpatterns = [
    path('', views.api_root, name='home'),
    path('tasks/', views.TaskListCreateView.as_view(), name='tasks_list_create_api'),
    path('task/<int:pk>', views.TaskDetailUpdateDeleteView.as_view(), name='task_retrieve_update_destroy_api'),
]

TaskManagement/todo/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'todo'
urlpatterns = [    
    path('register/', views.RegisterView.as_view(success_url=reverse_lazy('login')) , name='register'),  
    path('', views.TaskListCreateView.as_view(), name='list_create'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.TaskUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete', views.TaskDeleteView.as_view(), name='delete'),     
]

TaskManagement/todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
status = [
    ('Pending', 'Pending'),
    ('In Progress', 'In Progress'),
    ('Done', 'Done'),
]

class Task(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)                                    # owner    
    title = models.CharField(max_length=100, blank=False)                                        # title
    description = models.TextField(blank=True)                                                   # description
    created_time = models.DateTimeField(auto_now_add=True)                                       # creation time
    updated_time = models.DateTimeField(auto_now=True)                                           # update time
    status = models.CharField(max_length=15, choices=status, null=False, default='Pending')      # status
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_time']
    

TaskManagement/todo/forms.py
from django import forms
from .models import Task

class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']
        
class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'status']
        
class searchForm(forms.Form):
    search = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'search...'}), required=False)      

TaskManagement/todo/views.py
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.views import APIView, Response

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect,render, get_object_or_404
from django.contrib.auth.models import User
from django.views.generic import CreateView
from django.urls import reverse
from django.db.models import Q
from django.contrib import messages

from .models import Task
from .forms import TaskCreateForm, TaskUpdateForm, searchForm

# Create your views here.

class RegisterView(SuccessMessageMixin, CreateView):    
    model = User
    template_name = 'registration/register.html'
    form_class =  UserCreationForm     
    success_message = "User added"
    
    def get_form(self, form_class=None):
        form = super().get_form(form_class)        
        for field in form.fields.keys():
            form[field].help_text = None
        return form
        

class TaskListCreateView(LoginRequiredMixin, APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'todo/task_list_create.html'    
    
    def get(self, request):      
        form_task = TaskCreateForm()  
        form_search = searchForm()
        search = request.GET.get('search')        
        if search:
            task_list = Task.objects.filter(Q(title__icontains=search) | Q(description__icontains=search))
            form_search = searchForm(initial={'search': search})
            messages.success(request, f'search results for: {search}')
        else:
            task_list = Task.objects.all()
        context = {'task_list': task_list, 'form_task': form_task, 'form_search': form_search}
        return Response(context)       
    
    def post(self, request):
        form = TaskCreateForm(request.POST)
        if form.is_valid():            
            task = form.save(commit=False)
            task.owner = self.request.user            
            if not task.description:
                task.description = '-'            
            task.save()
            messages.success(request, 'Task added')
            return redirect(reverse('todo:list_create'))          
        tasks = Task.objects.all()
        return Response({'task_list': tasks, "form":form})
                        
    
class TaskDetailView(LoginRequiredMixin, APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'todo/task_detail.html'
    
    def get(self, request, pk):
        try:
            task = Task.objects.get(pk=pk)
        except:            
            return render(request, 'todo/error.html', {'error':'Task not found!'})        
        context = {'task': task}
        return Response(context)
    

class TaskDeleteView(LoginRequiredMixin, APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'todo/task_confirm_delete.html'    
    
    def get(self, request, pk):
        try:
            task = Task.objects.get(pk=pk)
            if task.owner != self.request.user:
                return render(request, 'todo/error.html', {'error': 'This task does not belong to you!'})
        except:
            return render(request, 'todo/error.html', {'error': 'Task not found!'})
        return Response({'task': task})
    
    def post(self, request, pk):        
        task = get_object_or_404(Task, pk=pk)
        if task.owner == self.request.user:
            task.delete()
            messages.success(request, 'Task deleted')
        else:
            messages.error(request, 'You are not authorized to delete this task!')
        return redirect(reverse('todo:list_create'))    
        
class TaskUpdateView(LoginRequiredMixin, APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'todo/task_form.html'
    
    def get(self, request, pk):
        try:
            task = Task.objects.get(pk=pk)                        
            if task.owner != self.request.user:
                return render(request, 'todo/error.html', {'error': 'This task does not belong to you!'})
        except:
            return render(request, 'todo/error.html', {'error': 'Task not found!'})
        form = TaskUpdateForm(instance=task)
        return Response({'form': form})
    
    def post(self, request, pk):
        try:
            task = Task.objects.get(pk=pk)                        
            if task.owner != self.request.user:
                return render(request, 'todo/error.html', {'error': 'This task does not belong to you!'})
        except:
            return render(request, 'todo/error.html', {'error': 'Task not found!'})
        form = TaskUpdateForm(request.POST, instance=task)
        if form.is_valid():            
            if not task.description:
                task.description = '-'
            form.save()             
            messages.success(request, 'Task updated')
            return redirect(reverse('todo:list_create'))
        return redirect(reverse('todo:list_create'))    

TaskManagement/todo/templates/todo/error.html
{% extends 'main-base.html' %}

{% block title %}
    Error
{% endblock %}

{% block main %}
    <h1>{{ error }}</h1>
    <button type="button" onclick="navigateToLink()" class="btn btn-secondary mt-3 mx-2">Back</button>

    <script>
        function navigateToLink() {
            window.location.href = "{% url 'todo:list_create' %}";
        }
    </script>
{% endblock %}

TaskManagement/todo/templates/todo/task_confirm_delete.html
{% extends 'main-base.html' %}
{% load humanize %}

{% block title %}
    Delete
{% endblock %}

{% block main %}

    <form action="" method="post" class="d-flex flex-column justify-content-center align-items-center">
        {% csrf_token %}    
        <div class="p-3 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3">Deleting a Task is considered a permenant action. Continue?</div>    
        <div class="d-flex justify-content-center">
            <input type="submit" value="Yes, delete." class="btn btn-danger mt-3 mx-2">
            <button type="button" onclick="navigateToLink()" class="btn btn-secondary mt-3 mx-2">Back</button>
        </div>        
    </form>

    <script>
        function navigateToLink() {
            window.location.href = "{% url 'todo:list_create' %}";
        }
    </script>
{% endblock %}

TaskManagement/todo/templates/todo/task_detail.html
{% extends 'main-base.html' %}
{% load humanize %}

{% block title %}
    Detail
{% endblock %}

{% block main %}
    {% if task.owner == request.user %}
        <div class="w-100 d-flex">
            <li class="list-group-item list-group-item-primary p-3 rounded-2 m-1 fs-2 w-100 text-break">
                <p>
                    Title: {{ task.title }} ( <a href="{% url 'todo:edit' task.id %}" class="link-primary link-offset-1 link-underline-opacity-25 link-underline-opacity-100-hover">Update</a> | <a href="{% url 'todo:delete' task.id %}" class="link-danger link-offset-1 link-underline-opacity-25 link-underline-opacity-100-hover">Delete</a> )
                </p>
                <p class="fs-4">
                    description: {{ task.description }}
                </p>
                <p class="fs-5">
                    created {{ task.created_time | naturaltime }} | updated {{ task.updated_time | naturaltime }}
                </p>
                <p class="fs-5">
                    status: {{ task.status }}
                </p>
                <p class="fs-6">
                    posted by {{ task.owner }}
                </p>
            </li>
        </div>
    {% else %}
        <div class="w-100 d-flex">
            <li class="list-group-item list-group-item-secondary p-3 rounded-2 m-1 fs-2 w-100 text-break">
                <p>
                    Title: {{ task.title }}
                </p>
                <p class="fs-4">
                    description: {{ task.description }}
                </p>
                <p class="fs-5">
                    created {{ task.created_time | naturaltime }} | updated {{ task.updated_time | naturaltime }}
                </p>
                <p class="fs-5">
                    status: {{ task.status }}
                </p>
                <p class="fs-6">
                    posted by {{ task.owner }}
                </p>
            </li>                                    
        </div>
    {% endif %}
    <button type="button" onclick="navigateToLink()" class="btn btn-secondary mt-3">Back</button>

    <script>
        function navigateToLink()
        {
            window.location.href = "{% url 'todo:list_create' %}";
        }
    </script>
{% endblock %}

TaskManagement/todo/templates/todo/task_form.html
{% extends 'main-base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Update
{% endblock %}

{% block main %}
    <form action="" class="d-flex flex-column justify-content-center align-items-center w-100" method="post">
        {% csrf_token %}
        {{ form | crispy }} 
        <div class="d-flex justify-content-center">
            <input type="submit" class="btn btn-primary mt-3 mx-2">
            <button type="button" onclick="navigateToLink()" class="btn btn-secondary mt-3 mx-2">Back</button>
        </div>           
    </form>

    <script>
        function navigateToLink() {
            window.location.href = "{% url 'todo:list_create' %}";
        }
    </script>
{% endblock %}

TaskManagement/todo/templates/todo/task_list_create.html
{% extends 'main-base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Tasks
{% endblock %}

{% block main %}
    <h1 class="display-2 px-5 mb-3 border-bottom">
        Create Task
    </h1>    
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    <form action="{% url 'todo:list_create' %}" class="d-flex flex-column justify-content-center align-items-center border-bottom border-dark w-100 pb-3" method="post">
        {% csrf_token %}
        {{ form_task | crispy }} 
        <div class="d-flex justify-content-center">
            <input type="submit" class="btn btn-primary mt-3">            
        </div>   
        <hr>            
    </form>
    <hr>
    <h1 class="display-2 px-5 my-3 border-bottom">
        Tasks        
    </h1>    
    <form action="{% url 'todo:list_create' %}" class="d-flex justify-content-center align-items-center mb-5">
        {{ form_search | crispy }}
        <input type="submit" class="btn btn-primary mx-2" value="search">
        <a href="{% url 'todo:list_create' %}" class="btn btn-secondary">clear</a>
    </form>    
    {% for task in task_list %}
        {% if task.owner == request.user %}
        <li class="list-group-item list-group-item-primary p-3 rounded-2 m-1 w-100 text-break fs-2">
            <p>
                <a href="{% url 'todo:detail' task.id %}" class="link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">Title: {{ task.title }}</a> ( <a href="{% url 'todo:edit' task.id %}" class="link-primary link-offset-1 link-underline-opacity-25 link-underline-opacity-100-hover">Update</a> | <a href="{% url 'todo:delete' task.id %}" class="link-danger link-offset-1 link-underline-opacity-25 link-underline-opacity-100-hover">Delete</a> )
            </p>
            <p class='fs-4 text-black'>
                status: {{ task.status }}
            </p>
            <p class="fs-6">
                posted by {{ task.owner }}
            </p>
        </li>
        {% else %}
            <li class="list-group-item list-group-item-secondary p-3 rounded-2 m-1 w-100 text-break fs-2">
                <p>
                    <a href="{% url 'todo:detail' task.id %}" class="link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">Title: {{ task.title }}</a>
                </p>
                <p class='fs-4 text-black'>
                    status: {{ task.status }}
                </p>
                <p class="fs-6">
                    posted by {{ task.owner }}
                </p>
            </li>
        {% endif %}
    {% empty %}
        <div class="alert alert-danger" role="alert">
            No Task Yet
        </div>
    {% endfor %}    

{% endblock %}